queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
      - check-success=DCO
      - check-success=validation
      - label!=do-not-merge
      - label=ready-to-merge
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=DCO
      - check-success=validation
    merge_method: merge
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
